/* Backup of original GameUI with embedded canvas/game logic. */
/* This file was autogenerated as a snapshot before removing the inlined game loop.
   Keep this file for reference or restore if needed. */

export const __GAMEUI_BACKUP__ = true;
